CREATE TABLE IF NOT EXISTS `proxy_ip` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `ip` varchar(50) NOT NULL COMMENT 'IP地址',
  `port` int NOT NULL COMMENT '端口',
  `country` varchar(50) DEFAULT NULL COMMENT '国家',
  `location` varchar(100) DEFAULT NULL COMMENT '位置',
  `type` varchar(10) DEFAULT NULL COMMENT '类型',
  `anonymity` varchar(20) DEFAULT NULL COMMENT '匿名性',
  `available` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否可用',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `last_validate_time` datetime DEFAULT NULL COMMENT '最后验证时间',
  `validate_count` int NOT NULL DEFAULT '0' COMMENT '验证次数',
  `available_count` int DEFAULT NULL COMMENT '可用次数',
  `unavailable_count` int DEFAULT NULL COMMENT '不可用次数',
  `response_time` bigint DEFAULT NULL COMMENT '响应时间',
  `request_time` bigint DEFAULT NULL COMMENT '请求时间',
  `use_time` bigint DEFAULT NULL COMMENT '使用时间',
  `available_rate` decimal(5,3) DEFAULT NULL COMMENT '可用率',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ip_port_type` (`ip`,`port`,`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='代理IP表'; 